# Your First Machine Learning Models
### How to build them scikit-learn

This notebook is being presented for a tutorial at PyCon 2026. It will cover the fundamentals of machine learning and all of the key steps and code to building, scoring, and tuning machine learning models in scikit-learn. This notebook is authored by Corey Wade, Berkeley Coding Academy.

# Linear Regression

The first model we will use is Linear Regression. First, we need to access some data. Then we need to find one column from the data that may be predicted from the other columns. We call this special column, what we want to predict in the future, y. The way Linear Regression works is that every other column gets a weight, a multiplier, that is summed with all the other columns * weights with the goal of getting as close as possible to y.

Machine Learning happens when the algorithm finds the best possible weights, the multipliers, and returns a mathematical model. The mathematical model takes each column of data as its input, the X values, and what it is trying to predict, what we designate as y, as the output. It's a challenging problem because there are so many rows of data. The same model is used on all the rows. The predictions may work well on some rows, and not as well on other rows. After finding a model, we need to score it, to see how well it performed.

We will download the data directly from the folder, but here is the url where the data is stored - you can access directly from a raw csv file in github via a url as well: https://media.githubusercontent.com/media/PacktPublishing/Hands-On-Gradient-Boosting-with-XGBoost-and-Scikit-learn/refs/heads/master/Chapter02/bike_rentals_cleaned.csv

In [1]:
# Load provided data (raw CSV file) and show first five rows
file = 'bike_rentals_cleaned.csv'
import pandas as pd
df = pd.read_csv(file)
df.head()

,instant,season,yr,mnth,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed,cnt
0,1,1.0,0.0,1.0,0.0,6.0,0.0,2,0.344167,0.363625,0.805833,0.160446,985
1,2,1.0,0.0,1.0,0.0,0.0,0.0,2,0.363478,0.353739,0.696087,0.248539,801
2,3,1.0,0.0,1.0,0.0,1.0,1.0,1,0.196364,0.189405,0.437273,0.248309,1349
3,4,1.0,0.0,1.0,0.0,2.0,1.0,1,0.200000,0.212122,0.590435,0.160296,1562
4,5,1.0,0.0,1.0,0.0,3.0,1.0,1,0.226957,0.229270,0.436957,0.186900,1600

In [2]:
# Learn more about the data including columnn types and non-vull values
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 731 entries, 0 to 730
Data columns (total 13 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   instant     731 non-null    int64
 1   season      731 non-null    float64
 2   yr          731 non-null    float64
 3   mnth        731 non-null    float64
 4   holiday     731 non-null    float64
 5   weekday     731 non-null    float64
 6   workingday  731 non-null    float64
 7   weathersit  731 non-null    int64
 8   temp        731 non-null    float64
 9   atemp       731 non-null    float64
 10  hum         731 non-null    float64
 11  windspeed   731 non-null    float64
 12  cnt         731 non-null    int64
dtypes: float64(10), int64(3)
memory usage: 74.4 KB

To frame a machine learning problem, think about what would be interesting to predict from the data. For the dataset at hand, it would be interesting to predict the number of bike rentals on a given day, provided that you know the weather and the day of the week. You must have access to the data that you are trying to predict in advance for all supervised learning problems. The model needs data to train on, or to learn from. The idea here is that we are going to create a mathematical model when we have all of the data, and we are going to use that model to make predictions when we only have some of the data.

In [3]:
# Split the data into X, the input to the function, and y, the output, what you are trying to predict
y = df.iloc[:, -1] # last col of data
X = df.iloc[:,:-1] # every other col beside the last
X.head() # show X, the input to the model

,instant,season,yr,mnth,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed
0,1,1.0,0.0,1.0,0.0,6.0,0.0,2,0.344167,0.363625,0.805833,0.160446
1,2,1.0,0.0,1.0,0.0,0.0,0.0,2,0.363478,0.353739,0.696087,0.248539
2,3,1.0,0.0,1.0,0.0,1.0,1.0,1,0.196364,0.189405,0.437273,0.248309
3,4,1.0,0.0,1.0,0.0,2.0,1.0,1,0.200000,0.212122,0.590435,0.160296
4,5,1.0,0.0,1.0,0.0,3.0,1.0,1,0.226957,0.229270,0.436957,0.186900

In [4]:
# Verify that y is the bike rental counts, what we are trying to predict
y.head()

0     985
1     801
2    1349
3    1562
4    1600
Name: cnt, dtype: int64

In [5]:
# Build and score a Linear Regression Model using the scikit-learn library
from sklearn.linear_model import LinearRegression
model = LinearRegression() # initialize model
model.fit(X, y) # this is where ML happens, where the algorithm finds optimal weights
model.score(X,y) # see how well the model performed on the data

0.8014463799424516

The model received a default R2 score of 0.80. You can think of this as 80% of the data is explained by the model. This is a solid score to start with, but we can do better. The reality is that Linear Regression is rarely the best model to use because data in the real world is rarely linear. 

It's pretty amazing that we built a machine learning model in four lines of code. This is the power and beauty of the scikit-learn library. It does the heavy lifting for you. The model.fit(X, y) is where the machine learning happens. Random weights are assigned, and a bad score results, but the weights are then updated based on whether the scores are too high or too low using a process called gradient descent. The goal of gradient descent is to update the weights until the error is minimized.

Let's see what else we can do with our model.

In [6]:
# Get the weights! (Also called the multipliers, or coefficients)
model.coef_

array([   -8.0719644 ,   506.8269428 ,  4993.46974708,   208.04685661,
        -523.26262121,    69.22225377,   121.56196695,  -623.56940671,
        2187.90318073,  3386.60991933,  -965.1047639 , -2513.57689857])

In [7]:
# Make predictions! We will take the last five rows since they are properly formatted
model.predict(X.tail())

array([2418.81022737, 3124.34847629, 2942.01983548, 2802.59267354,
       2526.39200445])

In [8]:
# Compare predictions with actual values
y.tail()

726    2114
727    3095
728    1341
729    1796
730    2729
Name: cnt, dtype: int64

Before finding better models to predict bike rentals, let's consider another type of machine learning problem.

# Logistic Regression

Classification is another type of Machine Learning problem. Instead of trying to get as close as possible to a correct numerical value, as in Linear Regression, you might want to classify data into two or more groups. The question here is a yes/no type of question. Does the patient have a heart disease? Yes or no? It's standard that 1 is yes, and 2 is no. To correctly predict this type of problem we need a different type of model, one that classifies data into two or more groups. Logistic Regression is one such model.

Logistic Regression is similar to Linear Regression. It takes all of the X values as input, finds weights for the values, and sums them together. But at the very end, the numerical value is placed into the sigmoid equation which is an elongated S-curve between 0 and 1 (See wikipedia entry: https://en.wikipedia.org/wiki/Sigmoid_function). If it's closer to 1, the row is classified as a 1, and if it's closer to 0, the row is classified as a 0.

Let's look at a dataset that requires classification.

In [9]:
# Load and show heart disease dataset
file = 'heart_disease.csv'
df2 = pd.read_csv(file)
df2.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1

In [10]:
# Split data into X and y - target, is 1 if they have a heart disease, 0 otherwise
y2 = df2.iloc[:,-1]
X2 = df2.iloc[:, :-1]
X2.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2

In [11]:
# Build and score a Logistic Regression Model
from sklearn.linear_model import LogisticRegression
model = LogisticRegression(max_iter=5000)
model.fit(X2, y2)
model.score(X2, y2)

0.8481848184818482

Our model correctly predicted whether patients had heart diseases in 85% of cases.

In [12]:
# Check weights
model.coef_

array([[-0.00327871, -1.45066968,  0.81210785, -0.0184621 , -0.00395159,
         0.01120555,  0.41530265,  0.02324108, -0.84159312, -0.53818402,
         0.50028131, -0.72896753, -0.84563496]])

In [13]:
# Select row to predict and modify the values - what does it take for a patient to get a healthy heart?
model.predict([[36,1,2,110,233,1,0,150,0,2.3,0,0,1]])

/opt/anaconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(

array([1])

In [14]:
# Silence warnings (change to 'default' to bring warnings back)
import warnings
warnings.filterwarnings('ignore')

# Tree-based Models

Now let's try a stronger model on our original dataset, a Decision Tree. A Decision Tree splits the data multiple times in an effort to find the desired y-value during training, like the game 20 questions. For instance, a Decision Tree might conclude that if it's a summer weekday and the temperature is above 70 degrees F and less than 80 degrees F and it is not a holiday then the company can expect 2100 bike rentals (made up example). Let's try a Decision Tree on the actual dataset and see how it performs.

In [15]:
# Build and score Decision Tree
from sklearn.tree import DecisionTreeRegressor
model = DecisionTreeRegressor()
model.fit(X, y)
model.score(X,y)

1.0

Amazing! We got a perfect score, so we can now retire. Not so fast! Anytime you get a perfect score in machine learning something is likely wrong. In this case, the issue is that we have perfectly predicted all rows for only the data that we trained on. In other words, we have been successful at "curve fitting," meaning that our mathematical model fits the curve perfectly. But at what cost? At the cost of making generalized predictions to new data. 

In effect, we are overfitting the model to the training data. (See the following to learn more about overfitting: https://en.wikipedia.org/wiki/Overfitting) We need a model that will perform well on unseen test data. How do we check this? We use sklearn to split the data for us, holding back some of the data that the model did not train on to score against. This is it how it works in the real world. It's not a game of curve-fitting. It's a game of making predictions about an unknown future. Let's split the data and see how the results differ.

In [16]:
# Split data into a training and test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y)

In [17]:
# Fit model on training set, and score on test set
model = DecisionTreeRegressor()
model.fit(X_train, y_train)
model.score(X_test, y_test)

0.7747683160946531

This is a more realistic R2 score. The model successfully predicts between 70 and 80 percent of the data (it varies due to randomness in the model). Since it successfully predicted 100 percent of the training data, the model is overfitting. We can adjust the model so that it does not overfit the data so much. One parameter we can adjust to prevent overfitting is max_depth, the number of times we split the data. If you split the data an unlimited number of times, you can always find perfect predictions. Let's lower max_depth from the unlimited (but finite) default and see what happens.

In [18]:
# Build and score Decision Tree by varying max_depth
model = DecisionTreeRegressor(max_depth=8)
model.fit(X_train, y_train)
model.score(X_test, y_test)

0.7719563022021968

By modifying max_depth, you can improve the test score. If you run the above cell multiple times, you keep getting different scores. There is some randomness in Decision Trees choosing their splits. How can we steady these predictions? One idea is to build multiple Decision Trees and take their average. This is called a Random Forest.

In [19]:
# Build and score Random Forest
from sklearn.ensemble import RandomForestRegressor
model = RandomForestRegressor(max_depth=8, n_estimators=50)
model.fit(X_train, y_train)
model.score(X_test, y_test)

0.9167281899644435

Another idea is to build Decision Trees sequentially and to train on the errors of the previous model. This is called Gradient Boosting, and is one of the top ML algorithms for supervised learning, along with Random Forests.

In [20]:
from sklearn.ensemble import GradientBoostingRegressor
# Gradient Boosting is based on starting with trees that are more general so max_depth is usually lower
model = GradientBoostingRegressor(max_depth=4) 
model.fit(X_train, y_train)
model.score(X_test, y_test)

0.9136516650485904

# Cross-validation and Scoring Metrics

Another place of randomness is train_test_split. Rerun it above and the following code and see what happens. The test set seems to hold a lot of importance. Is holding back one test set really the best approach?

In Machine Learning, it is standard to hold back a test set until the very end after fine-tuning and finalizing a model. In the meantime, it's preferrable to have another validation set that we can use to validate how well the model performs on unseen data when we make changes to the parameters with the goal of improving the model. We want to be able to experiment without compromising the test set. 

An optimal solution is to use cross-validation (See https://en.wikipedia.org/wiki/Cross-validation_(statistics)#/media/File:K-fold_cross_validation_EN.svg), a technique that will split our training data into 5 or more (sometimes less) different validation sets. Then we can score the model 5 different times, on the 5 different test sets, and take the average of these test sets to get a better idea of how the model performs. Note that the each time there is a new test set, a new 20% of the data is selected, and the remaining 80% is held back as the new training data. By using cross-validation we are not as dependent upon what portion of the data is held back as our validation set.

In [21]:
# Peform cross-validation on a Random Forest
from sklearn.model_selection import cross_val_score
model=RandomForestRegressor()
scores = cross_val_score(model, X_train, y_train, scoring='r2', cv=5)
print(scores)
print(scores.mean())

[0.8688556  0.84938033 0.82911723 0.82839029 0.90052016]
0.8552527243781487

In [22]:
# Perform cross-validation on Gradient Boosting
model=GradientBoostingRegressor(max_depth=4)
scores = cross_val_score(model, X_train, y_train, scoring='r2', cv=5)
print(scores)
print(scores.mean())

[0.88765961 0.84874459 0.84100206 0.84741019 0.9016426 ]
0.865291809887202

These scores are more robust as they have been performed on 5 different validation sets.

As a final adjustment in this section, let's take a look at changing the scoring metric. An R2 scoring metric leaves a lot to be desired. There are many scoring metrics to choose from. The root mean squared error is standard in regression models. It takes the square root of the sum of the squared errors of each prediction. The nice thing about the RMSE is that it's easier to interpret. It tells us how far off the predictions are on average from the expected value.

In [23]:
# Use RMSE on Gradient Boosting
model=GradientBoostingRegressor()
# We first use the mean squared error - it's negative because sklearn scoring defaults are the higher the better
mse = cross_val_score(model, X_train, y_train, scoring='neg_mean_squared_error', cv=5)
rmse = (-mse)**0.5 # make positive and take root for RMSE - closer to 0 is better
print(rmse)
print(rmse.mean())

[653.79896996 674.11001352 741.58907409 749.81541646 613.49550982]
686.5617967723053

We can now interpret the score much better. The model is off by this many bike rentals on average. Is this good or bad? Let's check against the standard deviation of the y-column.

In [24]:
# Get descriptive statistics of y
y.describe()

count     731.000000
mean     4504.348837
std      1937.211452
min        22.000000
25%      3152.000000
50%      4548.000000
75%      5956.000000
max      8714.000000
Name: cnt, dtype: float64

An RMSE that is about 1/3 the STD is actually doing fairly well.

# Fine-tuning models

Now let's go through the whole process and fine-tune a model. The idea of fine-tuning a model is choosing optimal parameters to give the best possible predictions based on the question at hand. Let's return to the heart disease data. Let's say that we want to screen patients who may be at risk of heart disease. This is very different than trying to make an accurate determination if someone has a heart disease. The latter is called precision, and the former is called recall. (See https://en.wikipedia.org/wiki/Precision_and_recall)

Another issue to consider with classification is the percentage of positive cases. It's helpful to train a model with the same number of positive cases in all splits. An imbalance in splits can lead to very low scores due to limited data. (Note that outliers can be removed in advance as part of the data-cleaning process.)

Let's split the data evenly, and learn about the precision and recall using a Confusion Matrix and Classification Report.

In [25]:
# Split classification data - use a random state for consistency
X2_train, X2_test, y2_train, y2_test = train_test_split(X2, y2, random_state=0)
# Stratify the data, which means keep it balanced
from sklearn.model_selection import StratifiedKFold
skfold = StratifiedKFold(n_splits=5, shuffle=True, random_state=0)

In [26]:
# Show confusion matrix and classification report for details on precision/recall
from sklearn.metrics import confusion_matrix, classification_report
from sklearn.ensemble import GradientBoostingClassifier
model = GradientBoostingClassifier(random_state=0)
model.fit(X2_train, y2_train)
y2_pred = model.predict(X2_test)
print(confusion_matrix(y2_test, y2_pred))
print(classification_report(y2_test, y2_pred))

[[24  9]
 [ 6 37]]
              precision    recall  f1-score   support

           0       0.80      0.73      0.76        33
           1       0.80      0.86      0.83        43

    accuracy                           0.80        76
   macro avg       0.80      0.79      0.80        76
weighted avg       0.80      0.80      0.80        76

You interpret the top matrix as correct along the diagonals. The scores are shown above. Note that the positive cases, the 1s, the patients with heart diseases, have a different precision and recall than patients with 0s, the healthy ones. The f1-score is a harmonic balance between precision and recall. Let's work on recall, flagging patients for heart diseases, and optimize parameters to get the best possible recall.

In [27]:
# GridSearchCV searches all possible parameters and chooses the combinations with the best score
from sklearn.model_selection import GridSearchCV

# Here is a customized function to find the best scores - note the scoring is recall, and cv is skfold as defined earlier.
def grid_search(params, clf=model):
    grid_clf = GridSearchCV(clf, params, scoring='recall', cv=skfold)
    grid_clf.fit(X2_train, y2_train)
    best_params = grid_clf.best_params_
    print("Best params:", best_params)
    best_score = (grid_clf.best_score_)
    print("Best score:", best_score)

In [28]:
# We start by modifying just max_depth, and n_estimaters - it will search  6*3=18 different combinations 
model = GradientBoostingClassifier(random_state=0)
grid_search({'max_depth':[1, 2, 3, 4, 6, 8],
            'n_estimators':[50, 100, 200]}) # with an average of 100 trees - this is 18*100=1800 ML models being built!

Best params: {'max_depth': 1, 'n_estimators': 50}
Best score: 0.8766666666666666

WARNING - You must be carefuly when using GridSearchCV. This code ran fairly quickly because our dataset is super small. GridSearchCV can be very time consuming. A nice alternative is to use RandomizedSearchCV. It will randomly check 10 or any other combinations that you want. When starting with a larger range of parameters, this is usually a better option.

In [29]:
# RandomizedSearchCV works the same way as GridSearchCV, but checks n (10 by default) random combinations
from sklearn.model_selection import RandomizedSearchCV
def random_search(params, clf=model):
    grid_clf = RandomizedSearchCV(clf, params, scoring='recall', cv=skfold, n_iter=10, random_state=0)
    grid_clf.fit(X2_train, y2_train)
    best_params = grid_clf.best_params_
    print("Best params:", best_params)
    best_score = (grid_clf.best_score_)
    print("Best score:", best_score)

In [30]:
# the following is a reasonable starting sample of params for a randomized search
model = GradientBoostingClassifier(random_state=0)
random_search(params={'subsample':[0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1], # percentage of rows to use per tree
       'min_samples_split':[2, 3, 4, 5, 6, 7, 8], # number of rows required before a split must be made
        'learning_rate':[0.001, 0.01, 0.1, 0.2, 0.4, 0.6], # rate at which model "learns", how quickly it steps toward minimum errors
        'max_depth':[1, 2, 3, 4, 5, 6, 8, 10], # number of splits the tree makes
        #'n_estimators':[25, 50, 100, 200, 400] # n_estimators, total number of trees, is often better used later
                     })

Best params: {'subsample': 0.8, 'min_samples_split': 6, 'max_depth': 6, 'learning_rate': 0.001}
Best score: 0.9833333333333334

In [31]:
# Narrow down the parameters and try again
random_search(params={'subsample':[0.6, 0.7, 0.8, 0.9, 1],
       'min_samples_split':[4, 5, 6, 7, 8],
        'learning_rate':[0.0001, 0.0005, 0.001, 0.01, 0.1],
        'max_depth':[2, 3, 4, 5, 6, 7],
        #'n_estimators':[25, 50, 100, 200, 400]
                     })

Best params: {'subsample': 0.9, 'min_samples_split': 6, 'max_depth': 6, 'learning_rate': 0.0001}
Best score: 1.0

We win again. Right? Remember the warnings about 100% accuracy? It turns out there is an easy way to get 100% recall. Just say every patient is at risk of having a heart disease. That way you are guaranteed not to miss anyone. When this happens, the model has not learned anything. Is this happening here? Let's check the confusion matrix and classifation report using the parameters above.

In [32]:
# Show confusion matrix and classification report
model = GradientBoostingClassifier(subsample=0.9, min_samples_split=6, max_depth=6, learning_rate=0.0001, random_state=0)
model.fit(X2_train, y2_train)
y2_pred = model.predict(X2_test)
print(confusion_matrix(y2_test, y2_pred))
print(classification_report(y2_test, y2_pred))

[[ 0 33]
 [ 0 43]]
              precision    recall  f1-score   support

           0       0.00      0.00      0.00        33
           1       0.57      1.00      0.72        43

    accuracy                           0.57        76
   macro avg       0.28      0.50      0.36        76
weighted avg       0.32      0.57      0.41        76

This is trouble. Since everything is showing up across from the 1, the model is predicting that all patients have a heart diseases. Part of the issue is that our dataset is so small. How can we work around this? We can modify our search using the f1-score instead. Recall that f1 is the harmonic balance between precision and recall.

In [33]:
# Combine functions into one with f1 scoring as default parameter
def params_search(params, clf=GradientBoostingClassifier(random_state=0), random=False, scoring='f1'):
    if random:
        grid_clf = RandomizedSearchCV(clf, params, scoring='f1', cv=skfold, n_iter=10, random_state=0)
    else:
        grid_clf = GridSearchCV(clf, params, scoring='f1', cv=skfold)
    grid_clf.fit(X2_train, y2_train)
    best_params = grid_clf.best_params_
    print("Best params:", best_params)
    best_score = (grid_clf.best_score_)
    print("Best score:", best_score)

In [34]:
# Search params using f1-score
params_search(random=True, params={'subsample':[0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1],
       'min_samples_split':[2, 3, 4, 5, 6, 7, 8],
        'learning_rate':[0.001, 0.01, 0.1, 0.2, 0.4, 0.6],
        'max_depth':[1, 2, 3, 4, 5, 6, 8, 10],
        #'n_estimators':[25, 50, 100, 200, 400]
                     })

Best params: {'subsample': 0.4, 'min_samples_split': 6, 'max_depth': 10, 'learning_rate': 0.01}
Best score: 0.8421083814274842

In [35]:
# Narrow params
params_search(random=True, params={'subsample':[0.3, 0.4, 0.5, 0.6, 0.7, 0.8],
       'min_samples_split':[5, 6, 7],
        'learning_rate':[0.005, 0.01, 0.05, 0.1],
        'max_depth':[2, 5, 8, 10, 12,],
        #'n_estimators':[25, 50, 100, 200, 400]
                     })

Best params: {'subsample': 0.3, 'min_samples_split': 7, 'max_depth': 5, 'learning_rate': 0.01}
Best score: 0.8564226884226883

In [36]:
# Narrow params
params_search(random=True, params={'subsample':[0.3, 0.4, 0.5],
       'min_samples_split':[6, 7, 8],
        'learning_rate':[0.075, 0.01, 0.025],
        'max_depth':[1, 2, 3, 4, 5, 6],
        #'n_estimators':[25, 50, 100, 200, 400]
                     })

Best params: {'subsample': 0.5, 'min_samples_split': 7, 'max_depth': 2, 'learning_rate': 0.025}
Best score: 0.8565687956143005

In [37]:
# Check all values with gridsearch
params_search(params={'subsample':[0.4, 0.5, 0.6],
       'min_samples_split':[7],
        'learning_rate':[.015, 0.025, 0.035],
        'max_depth':[1, 2, 3],
        #'n_estimators':[25, 50, 100, 200, 400]
                     })

Best params: {'learning_rate': 0.015, 'max_depth': 3, 'min_samples_split': 7, 'subsample': 0.4}
Best score: 0.8637987421383648

In [38]:
# Add n_estimators
params_search(params={'subsample':[0.3, 0.4],
       'min_samples_split':[7],
        'learning_rate':[0.015, 0.002, 0.01],
        'max_depth':[1, 2],
        'n_estimators':[10, 25, 50, 100, 200]
                     })

Best params: {'learning_rate': 0.015, 'max_depth': 1, 'min_samples_split': 7, 'n_estimators': 200, 'subsample': 0.4}
Best score: 0.8652514892514892

In [39]:
# Narrow params
params_search(params={'subsample':[0.4],
       'min_samples_split':[7],
        'learning_rate':[0.008, 0.015],
        'max_depth':[1, 2, 3],
        'n_estimators':[150, 200, 250]
                     })

Best params: {'learning_rate': 0.015, 'max_depth': 1, 'min_samples_split': 7, 'n_estimators': 200, 'subsample': 0.4}
Best score: 0.8652514892514892

We could keep searching, but it could be that our model cannot improve upon this f1-score. Let's check this one in the confusion matrix and classification report.

In [40]:
# Show confusion matrix and classification report
model = GradientBoostingClassifier(subsample=0.4, min_samples_split=7, max_depth=1, learning_rate=0.015, random_state=0, n_estimators=200)
model.fit(X2_train, y2_train)
y2_pred = model.predict(X2_test)
print(confusion_matrix(y2_test, y2_pred))
print(classification_report(y2_test, y2_pred))

[[24  9]
 [ 4 39]]
              precision    recall  f1-score   support

           0       0.86      0.73      0.79        33
           1       0.81      0.91      0.86        43

    accuracy                           0.83        76
   macro avg       0.83      0.82      0.82        76
weighted avg       0.83      0.83      0.83        76

This is an excellent recall score for the patients with heart disease. There is real value here. This model could potentially be used to help medical staff warn patients who may be at increased risk of heart disease. Now let's finalize the model.

# Finalize Model

Generally speaking, models are finalized when there will be no more training/testing in the foreseeable future. Obviously models can be retrained when more data comes in. A couple of helpful steps in finalizing models: 1) Convert data to numpy arrays to avoid the need of labels, and 2) Go back and train the model on all the data. Why? We are done training and testing. The more data, the better.

In [41]:
# Convert data to numpy arrays
import numpy as np
X_np = np.array(X2)
y_np = np.array(y2)

# Train model on all data as numpy arrays
model = GradientBoostingClassifier(subsample=0.5, min_samples_split=7, max_depth=1, learning_rate=0.1, n_estimators=200)
model.fit(X_np, y_np)

GradientBoostingClassifier(max_depth=1, min_samples_split=7, n_estimators=200,
                           subsample=0.5)

In [42]:
#Save models using pickle for future use
import pickle

# Save model to local machine
filename = 'final_model.sav'
pickle.dump(model, open(filename, 'wb'))

# Load the model from disk
load_model = pickle.load(open(filename, 'rb'))

# Check model
print(load_model)

GradientBoostingClassifier(max_depth=1, min_samples_split=7, n_estimators=200,
                           subsample=0.5)

As a bonus, you can show how influential each column was when building the model using feature_importances_. This is very valuable information.

In [43]:
# Show the influence of each column
model.feature_importances_

array([0.04587487, 0.03913517, 0.17470733, 0.05837522, 0.0754975 ,
       0.00206555, 0.01160482, 0.07410717, 0.06767711, 0.1044511 ,
       0.04281374, 0.153694  , 0.14999642])

In [44]:
# Zip columns and feature_importances_ into dict for greater readability
feature_dict = dict(zip(X2.columns, model.feature_importances_))

import operator
# Sort dict by values (as list of tuples)
sorted(feature_dict.items(), key=operator.itemgetter(1), reverse=True)

[('cp', np.float64(0.17470733214370457)),
 ('ca', np.float64(0.15369400175881306)),
 ('thal', np.float64(0.14999641664390395)),
 ('oldpeak', np.float64(0.10445109798937208)),
 ('chol', np.float64(0.07549750487244318)),
 ('thalach', np.float64(0.07410717316166299)),
 ('exang', np.float64(0.06767710947712509)),
 ('trestbps', np.float64(0.05837522406992626)),
 ('age', np.float64(0.045874869286442674)),
 ('slope', np.float64(0.04281373725515665)),
 ('sex', np.float64(0.03913516676078604)),
 ('restecg', np.float64(0.011604819462356138)),
 ('fbs', np.float64(0.002065547118307239))]

That's all! Feel free to check out my youtube playlist on machine learning that goes into greater detail on some of this code: https://www.youtube.com/playlist?list=PL5Rqo-gm0HkbvqOy-OvHpBs3XHiA9QpIY